Update

diff --git a/.github/workflows/main_maps-server-20241208.yml b/.github/workflows/main_maps-server-20241208.yml
--- a/.github/workflows/main_maps-server-20241208.yml
+++ b/.github/workflows/main_maps-server-20241208.yml
@@ -1,7 +1,3 @@
-# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
-# More GitHub Actions for Azure: https://github.com/Azure/actions
-# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions
-
 name: Build and deploy Python project to Azure Function App - maps-server-20241208
 
 on:
@@ -31,16 +27,21 @@ jobs:
 
       - name: Create and start virtual environment
         run: |
+          set -e
           python -m venv venv
           source venv/bin/activate
 
       - name: Install dependencies
-        run: pip install -r requirements.txt
+        run: |
+          set -e
+          pip install -r requirements.txt
 
       # Optional: Add step to run tests here
 
       - name: Zip artifact for deployment
-        run: zip release.zip ./* -r
+        run: |
+          set -e
+          zip release.zip ./* -r
 
       - name: Upload artifact for deployment job
         uses: actions/upload-artifact@v4
@@ -61,7 +62,9 @@ jobs:
           name: python-app
 
       - name: Unzip artifact for deployment
-        run: unzip release.zip     
+        run: |
+          set -e
+          unzip release.zip     
         
       - name: 'Deploy to Azure Functions'
         uses: Azure/functions-action@v1
@@ -71,3 +74,9 @@ jobs:
           slot-name: 'Production'
           package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
           publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_01CBD11C45FF4BC5A30B713CDDD58277 }}
+
+      - name: Display error if deployment fails
+        if: failure()
+        run: |
+          echo "Deployment failed. Here are the error logs:"
+          cat /tmp/azure/deployment_logs.log  # Adjust the log path as needed
