Update main_maps-server-20241208.yml

diff --git a/.github/workflows/main_maps-server-20241208.yml b/.github/workflows/main_maps-server-20241208.yml
--- a/.github/workflows/main_maps-server-20241208.yml
+++ b/.github/workflows/main_maps-server-20241208.yml
@@ -76,6 +76,8 @@ jobs:
           
       - name: pip install
         run: |        
-          python -m pip install --upgrade pip
-          python -m pip install -r requirements.txt
+          for package in $(cat requirements.txt); do
+            python -m pip install $package || echo "Failed to install $package"
+          done
+
           
